apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-ecommerce-config
  namespace: valkey-ecommerce
data:
  PORT: "5000"
  VALKEY_URL: "redis://valkey:6379"
  ALLOWED_ORIGINS: "http://localhost:3000,http://localhost"
