apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: valkey-ecommerce-ingress
  namespace: valkey-ecommerce
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: valkey-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: valkey-backend
                port:
                  number: 5000
